(prop "@base" (load "player"))
(prop "long" "This is a generic adult human male. There is nothing interesting about him at all.")
(prop "pronoun" "he")
(prop "label" "generic human male")
(prop "front-end-label" *"(this.label)")
